apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c6ehyhoou-go
  janus-idp.io/tekton: c6ehyhoou-go
  backstage.io/kubernetes-id: c6ehyhoou-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c6ehyhoou-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
